### ISSUE TITLE
"show ip/ipv6 interface" parser error if unicast RPF is configured on NX-OS

### ISSUE THREAD

**Issue by netgab** [CiscoTestAutomation/pyats#81] opened 2021-03-11 06:32 UTC
If using the Genie parser `show ip interface vrf all` or `show ipv6 interface vrf all` on NX-OS, an exception is raised if there are multiple **unicast RPF** parameters configured.

## Expected Behavior
Parsing of interface VLAN 10 using the following shortened configuration:
```
interface Vlan10
  # IP configuration and other parameters ...
  ip verify unicast source reachable-via any allow-default
  ipv6 verify unicast source reachable-via any allow-default
!
```
The corresponding output for `show ip interface vrf all` on this interface:
```
Vlan10, Interface status: protocol-down/link-down/admin-down, iod: 42,
  [...]
  IP unicast reverse path forwarding: loose allow default
  [...]
```
The corresponding output for `show ipv6 interface vrf all` on this interface:
```
Vlan10, Interface status: protocol-up/link-up/admin-up, iod: 42
  [...]
  IPv6 unicast reverse path forwarding: loose allow default
  [...]
```

## Current Behavior
The genie parser raises an exception with the unicast RPF configuration above.

## Possible Solution
File: show_interface.py
Change the regular expression in variable `p16` and `p14` to allow multiple words.
Original code
```
#IP unicast reverse path forwarding
p16 = re.compile(r'^\s*IP *unicast *reverse *path *forwarding:'
                  ' *(?P<unicast_reverse_path>\w+)$')
...
#IPv6 unicast reverse path forwarding
p14 = re.compile(r'^\s*IPv6 *unicast *reverse *path *forwarding:'
                  ' *(?P<ipv6_unicast_rev_path_forwarding>\w+)$')

```
Fixed code
```
#IP unicast reverse path forwarding
p16 = re.compile(r'^\s*IP *unicast *reverse *path *forwarding:'
                  ' *(?P<unicast_reverse_path>([\w\s]+))$')
...
#IPv6 unicast reverse path forwarding
p14 = re.compile(r'^\s*IPv6 *unicast *reverse *path *forwarding:'
                  ' *(?P<ipv6_unicast_rev_path_forwarding>([\w\s]+))$')

```

## Steps to Reproduce
```
ipv4IntInfo = curDevice.parse('show ip interface vrf all')
ipv6IntInfo = curDevice.parse('show ipv6 interface vrf all')
```

## Context (Environment)
```
You are currently running pyATS version: 21.2
Python: 3.6.12 [64bit]

  Package                      Version
  ---------------------------- -------
  genie                        21.2.1 
  genie.libs.clean             21.2   
  genie.libs.conf              21.2   
  genie.libs.filetransferutils 21.2   
  genie.libs.health            21.2   
  genie.libs.ops               21.2   
  genie.libs.parser            21.2.3 
  genie.libs.robot             21.2   
  genie.libs.sdk               21.2   
  genie.telemetry              21.2   
  genie.trafficgen             21.2   
  pyats                        21.2   
  pyats.aereport               21.2   
  pyats.aetest                 21.2   
  pyats.async                  21.2   
  pyats.connections            21.2.1 
  pyats.contrib                21.2   
  pyats.datastructures         21.2   
  pyats.easypy                 21.2   
  pyats.kleenex                21.2   
  pyats.log                    21.2   
  pyats.reporter               21.2   
  pyats.results                21.2   
  pyats.robot                  21.2   
  pyats.tcl                    21.2   
  pyats.topology               21.2   
  pyats.utils                  21.2   
  unicon                       21.2   
  unicon.plugins               21.2   
```

**Comment by kazemy** [comment] 2021-04-02 18:31
@netgab,
Thank you for reaching out. A correction for this issue has been implemented and is in reviews. 
I will let you know when the fix is available.

**Comment by kazemy** [comment] 2021-04-06 20:10
@netgab - The issue is resolved and has been merged. It will be available in our next public release.
Thank you!

**Comment by tahigash** [comment] 2022-01-14 17:47
It seemed forgotten to close. closed.

**Closed by tahigash** 2022-01-14 17:47 UTC
