### ISSUE TITLE
pyats create with excel file getting error "expected str, bytes or os.PathLike object, not bool"

### ISSUE THREAD

**Issue by ccole10561** [CiscoTestAutomation/pyats#56] opened 2020-08-27 16:27 UTC
Hello, this might just be user error, but I could not find/figure out what I'm doing wrong.
When I try to use the pyats create testbed with a excel file I get the error "expected str, bytes or os.PathLike object, not bool". Any guidance would be appreciated 

Thanks Chris

**Comment by ccole10561** [comment] 2020-08-27 16:45
I figured it out, the examples did not have a "=" between --path and --output, when I used --path=. it worked. 
Not sure why the example dont have it

**Comment by tahigash** [comment] 2020-08-27 19:04
@ccole10561 thanks for reporting above. I think it should work even with space. we will look into this. reopening this to check what wrong with it.

**Comment by ThomasJRyan** [comment] 2020-09-14 18:53
I am unable to reproduce this on version 20.8. What version of pyATS do you have installed?

**Comment by ccole10561** [comment] 2020-09-16 20:19
I ran the pyats version check

You are currently running pyATS version: 20.5
Python: 3.7.8 [64bit]

  Package                      Version
  ---------------------------- -------
  genie                        20.5   
  genie.libs.clean             20.5   
  genie.libs.conf              20.5   
  genie.libs.filetransferutils 20.5   
  genie.libs.ops               20.5   
  genie.libs.parser            20.5   
  genie.libs.robot             20.5   
  genie.libs.sdk               20.5   
  genie.telemetry              20.5   
  genie.trafficgen             20.5   
  pyats                        20.5   
  pyats.aereport               20.5   
  pyats.aetest                 20.5   
  pyats.async                  20.5   
  pyats.connections            20.5   
  pyats.contrib                20.5   
  pyats.datastructures         20.5   
  pyats.easypy                 20.5   
  pyats.kleenex                20.5   
  pyats.log                    20.5   
  pyats.reporter               20.5   
  pyats.results                20.5   
  pyats.robot                  20.5   
  pyats.tcl                    20.5   
  pyats.topology               20.5   
  pyats.utils                  20.5   
  unicon                       20.5   
  unicon.plugins               20.5

**Comment by jeaubin** [comment] 2020-09-23 18:52
@ccole10561  - Can you try with latest version and see if you can reproduce it

**Comment by tahigash** [comment] 2020-11-05 10:40
no update more than 1 month. closing this issue.

@ccole10561, if you see the same issue with latest release, please feel free to reopen.

**Closed by tahigash** 2020-11-05 10:40 UTC
