### ISSUE TITLE
pyats.topology.loader  dependency 

### ISSUE THREAD

**Issue by avidstrutt** [CiscoTestAutomation/pyats#48] opened 2020-04-30 22:11 UTC
Please assist.

When creating a testbed file 
$ genie create testbed --output yaml/testbed.yml --encode-password

I get following error. 
"pyats.topology.loader is a required dependency for this command. 'None' source cannot be found."

**Comment by tahigash** [comment] 2020-04-30 23:47
@avidstrutt I assume you are using latest `20.4`. and sorry for inconvenience. We've updated the syntax a bit on new release `20.4`.

Could you please try below command instead? 
```
pyats create testbed interactive --output test.yaml --encode-password
``` 
Error is not friendly. So, we will fix and improve it.

**Comment by avidstrutt** [comment] 2020-05-01 09:34
Thanks for your quick response Tahigash

I've tried the command, on (v.20.4) still no luck:(
'pyats create testbed interactive --output test.yaml --encode-password'

I've downgraded to genie (v.20.1) and now it works with command below :)
'genie create testbed --output yaml/testbed.yml --encode-password'

**Comment by tahigash** [comment] 2020-05-01 18:10
@avidstrutt hm. from 20.4, the command is part of `pyats.contrib` package. so we need to install like below. (or it will be installed if you use 'pip install pyats[full])

```
pip install pyats.contrib
```

Please check if the package exist with 20.4 and try again? if still doesn't work, please share below information.
```
python -V
pip list
(and output of pyats create command with error)

**Comment by tahigash** [comment] 2020-05-13 16:49
@avidstrutt the issue is resolved? if no update, I will close this issue. let me know if you still have issue.

I believe it's not relating to your issue directly. but we fixed some and released minor version up.
please do:
```
pip install pyats.contrib --upgrade
```
and also we've updated our doc how to use this command. please check updated doc as well.
https://pubhub.devnetcloud.com/media/genie-docs/docs/cli/genie_create.html#genie-create-testbed

**Comment by avidstrutt** [comment] 2020-05-14 17:41
Appreciate your help Takashi !

**Comment by tahigash** [comment] 2020-05-14 20:23
closing this issue. if you see the same even with updated package, please feel free to reopen.

**Closed by tahigash** 2020-05-14 20:23 UTC
