### ISSUE TITLE
Bug (unassigned variable) in routing parser, version 21.10 

### ISSUE THREAD

**Issue by maercu** [CiscoTestAutomation/pyats#136] opened 2021-11-04 08:30 UTC
Error in version 21.10

```
/lib/python3.9/site-packages/genie/libs/parser/iosxe/show_routing.py", line 454, in cli
    route_dict['active'] = active
UnboundLocalError: local variable 'active' referenced before assignment
```

**Comment by LukasMcClelland** [comment] 2021-11-08 15:30
Hi @maercu, thank you for bringing this issue to our attention. Are you interested in fixing this issue yourself and opening a PR? If not, that's OK. We can look after it

**Comment by LukasMcClelland** [comment] 2021-11-08 15:44
Closing because duplicate of https://github.com/CiscoTestAutomation/genieparser/issues/573

**Closed by LukasMcClelland** 2021-11-08 15:44 UTC
